name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: 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
          GIST_ID: 5a2c225fb11dbdf7d36e3d8e9be70b21
          TIMEZONE: Asia/Seoul
